# -*- coding: utf-8 -*-
"""to do list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5X_zhimZOhqPHVFNi_GzHQiAQYK6ByP
"""

class Task:
  def __init__(self):
    self.tasks = []


#Background of the To-Do-list

# add task
  def add_task(self, task, deadline):
    self.tasks.append({"task": task, "deadline": deadline})
    print(" -----Task added successfully----- ")

#remove task
  def remove_task(self, task):
    for t in self.tasks:
      if t["task"] == task:
        self.tasks.remove(t)
        print(" -----Task removed successfully----- ")
        return
  print(" -----Task not found----- ")

#view task
  def view_tasks(self):
    for i, task in enumerate(self.tasks):
      print(f"{i+1}. {task['task']} - {task['deadline']}")
    if not self.tasks:
      print(" -----No tasks found----- ")
      return

#clear task
  def clear_task(self):
    self.tasks.clear()
    print(" -----All tasks cleared successfully----- ")


#update deadline
  def update_deadline(self, task, new_deadline):
    for t in self.tasks:
      if t["task"] == task:
        t["deadline"] = new_deadline
        print(" -----Deadline updated successfully----- ")
        return
    print(" -----Task not found----- ")



todolist= Task()

# user interface

print("welcome to your to do list")
print("\n------To-Do-List------\n")
print("1. Add Task")
print("2. Remove Task")
print("3. View tasks")
print("4. Update Deadline")
print("5. Clear all tasks")
print("6. Exit")
print()

while True:
  try:
    welcome= int(input("Enter your choice : "))
    print()
  except ValueError:
    print("Enter valid index number between 1 and 6")
    print()
    continue


  if welcome==1:
    print(" -----Add Task------ ")
    task= input("Enter a new task : ")
    deadline= input("Enter the deadline for the task : ")
    todolist.add_task(task, deadline)
    print()


  elif welcome==2:
    print(" -----Remove Task------ ")
    task= input("Enter the task to remove :  ")
    todolist.remove_task(task)
    print()


  elif welcome==3:
    print(" -----View tasks------ ")
    todolist.view_tasks()
    print()


  elif welcome==4:
    print(" -----Update Deadline------ ")
    task= input("Enter the task to update the deadline for :  ")
    if task not in [t["task"] for t in todolist.tasks]:
      print(" -----Task not found----- ")
      print()
      continue
    new_deadline= input("Enter the new deadline for the task :  ")
    todolist.update_deadline(task, new_deadline)
    print()


  elif welcome==5:
    print(" -----Clear all tasks------ ")
    todolist.clear_task()
    print()


  elif welcome==6:
    print(" -----Exit------ ")
    print(" -----Thank you for using our to-do-list----- ")
    print()
    break

  else:
   print("Enter valid index")
   print()